# Setup
title: arth
url: https://iveurne.github.io/me/
paginate: 1
baseurl: ""
permalink: :3

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
